@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post
Content-Type: application/json
Accept: application/json
withCredentials: true

{
"post": "new post",
"bgColor": "#f34292",
"privacy":"",
"gifUrl": "http://google.com/343523",
"profilePicture":"",
"feelings":""
}

###
GET {{baseUrl}}/{{urlPath}}/posts/all/1
Content-Type: application/json
Accept: application/json
withCredentials: true



###
POST {{baseUrl}}/{{urlPath}}/post/image/post
Content-Type: application/json
Accept: application/json
withCredentials: true

{
"post": "",
"bgColor": "",
"privacy":"",
"gifUrl": "",
"profilePicture":"",
"feelings":"",
"image":"not empty"
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
"username": "t a o 3",
"password": "9034098"
}

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true
